// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

namespace web.Migrations
{
    [DbContext(typeof(SpljocContext))]
    [Migration("20211108214515_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("web.Models.Bazen", b =>
                {
                    b.Property<int>("BazenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BazenID");

                    b.ToTable("Bazen");
                });

            modelBuilder.Entity("web.Models.Izvedba", b =>
                {
                    b.Property<int>("IzvedbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumUra")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NadomestniUciteljID")
                        .HasColumnType("int");

                    b.Property<int>("SkupinaID")
                        .HasColumnType("int");

                    b.HasKey("IzvedbaID");

                    b.HasIndex("NadomestniUciteljID");

                    b.HasIndex("SkupinaID");

                    b.ToTable("Izvedba");
                });

            modelBuilder.Entity("web.Models.Plavalec", b =>
                {
                    b.Property<int>("PlavalecID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRojstva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkupinaID")
                        .HasColumnType("int");

                    b.HasKey("PlavalecID");

                    b.HasIndex("SkupinaID");

                    b.ToTable("Plavalec");
                });

            modelBuilder.Entity("web.Models.Skupina", b =>
                {
                    b.Property<int>("SkupinaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BazenID")
                        .HasColumnType("int");

                    b.Property<int>("ProgaID")
                        .HasColumnType("int");

                    b.Property<int>("UciteljID")
                        .HasColumnType("int");

                    b.Property<int>("Ura")
                        .HasColumnType("int");

                    b.HasKey("SkupinaID");

                    b.HasIndex("BazenID");

                    b.HasIndex("UciteljID");

                    b.ToTable("Skupine");
                });

            modelBuilder.Entity("web.Models.Ucitelj", b =>
                {
                    b.Property<int>("UciteljID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumRojstva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priimek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrnaPostavka")
                        .HasColumnType("int");

                    b.HasKey("UciteljID");

                    b.ToTable("Ucitelj");
                });

            modelBuilder.Entity("web.Models.Izvedba", b =>
                {
                    b.HasOne("web.Models.Ucitelj", "NadomestniUcitelj")
                        .WithMany("Izvedbe")
                        .HasForeignKey("NadomestniUciteljID");

                    b.HasOne("web.Models.Skupina", "Skupina")
                        .WithMany("Izvedbe")
                        .HasForeignKey("SkupinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NadomestniUcitelj");

                    b.Navigation("Skupina");
                });

            modelBuilder.Entity("web.Models.Plavalec", b =>
                {
                    b.HasOne("web.Models.Skupina", "Skupina")
                        .WithMany("Plavalci")
                        .HasForeignKey("SkupinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skupina");
                });

            modelBuilder.Entity("web.Models.Skupina", b =>
                {
                    b.HasOne("web.Models.Bazen", "Bazen")
                        .WithMany("Skupine")
                        .HasForeignKey("BazenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Models.Ucitelj", "Ucitelj")
                        .WithMany("Skupine")
                        .HasForeignKey("UciteljID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bazen");

                    b.Navigation("Ucitelj");
                });

            modelBuilder.Entity("web.Models.Bazen", b =>
                {
                    b.Navigation("Skupine");
                });

            modelBuilder.Entity("web.Models.Skupina", b =>
                {
                    b.Navigation("Izvedbe");

                    b.Navigation("Plavalci");
                });

            modelBuilder.Entity("web.Models.Ucitelj", b =>
                {
                    b.Navigation("Izvedbe");

                    b.Navigation("Skupine");
                });
#pragma warning restore 612, 618
        }
    }
}
